---
- hosts: 127.0.0.1
  connection: local
  become: yes

  tasks:
      - name: Install MySQL
        apt: pkg={{ item }} state=present update_cache=yes
        with_items:
            - mysql-server
            - mysql-client
            - python-mysqldb

      - name: Enable MySQL Service
        service: 
            name: mysql 
            state: started
            enabled: true

      - name: Create DB
        mysql_db:
            name: "{{ lookup('env','DB_NAME') }}"
            state: present

      - name: Create DB User
        mysql_user:
            name: "{{ lookup('env','DB_USER') }}"
            host: "{{ lookup('env','DB_HOST') }}"
            password: "{{ lookup('env','DB_PASS') }}"
            priv: "{{ lookup('env','DB_NAME') }}.*:ALL"
            state: present
          
      - name: Copy my.cnf file
        template:
            src: my.cnf
            dest: /etc/mysql/my.cnf
        register: mycnf

      - name: Restart MySQL Service
        become: true
        service: name=mysql state=restarted
        when: mycnf.changed
        
      - name: Lookup IP
        shell: "aws ec2 describe-instances --filters 'Name=tag:Name,Values=Database' --query 'Reservations[*].Instances[*].PrivateIpAddress' --output=text"
        environment:
          AWS_ACCESS_KEY_ID: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
          AWS_DEFAULT_REGION: "{{ lookup('env','AWS_DEFAULT_REGION') }}"
          AWS_SECRET_ACCESS_KEY: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
        register: ip

      - name: Connect DB
        mysql_db:
            login_user: "{{ lookup('env','DB_USER') }}"
            login_host: "{{ ip.stdout }}"
            login_password: "{{ lookup('env','DB_PASS') }}"
            login_port: "{{ lookup('env','DB_PORT') }}"
            name: "{{ lookup('env','DB_NAME') }}"
            state: present
